[book]
authors = ["sevki"]
language = "en"
multilingual = false
src = "docs"
title = "JetStream Book"

[output.html]
additional-css = ["docs/styles.css"]
no-section-label = false
create-missing = false
