---
specs: 
  - name: jetstream
    prefix: r
    source_url: "https://github.com/sevki/jetstream"
    include: 
      - docs/specs/**/*.md
    impls: 
      - name: main
        include: 
          - components/**/*.rs
          - tests/**/*.rs
        exclude: 
          - target/**
          - .direnv/**/*
        test_include: []
