[package]
name = "mdbook-changelog"
version = "15.2.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.101"
mdbook-core = "0.5.2"
mdbook-preprocessor = "0.5.2"
regex = "1.12.3"
serde_json = "1.0.149"
