[package]
name = "mdbook-changelog"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = "1.0.100"
mdbook-core = "0.5.2"
mdbook-preprocessor = "0.5.2"
regex = "1.12.2"
serde_json = "1.0.149"
