[package]
name = "jetstream_9p"
version = "8.0.6"
edition = { workspace = true }
description = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
documentation.workspace = true
[lib]
bench = false

[dependencies]
jetstream_macros = { version = "8.0.6", path = "../jetstream_macros" }
jetstream_wireformat = { version = "8.0.6", path = "../jetstream_wireformat" }
jetstream_rpc = { version = "8.0.6", path = "../jetstream_rpc" }
libc = "0.2.169"
async-trait = "0.1.85"
trait-variant = "0.1.2"
