[package]
name = "jetstream_macros"

authors = ["Sevki <s@sevki.io>", "The ChromiumOS Authors"]
version = "8.0.1"
edition = { workspace = true }
description = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
documentation = { workspace = true }
[dependencies]
# rust analyzer doesn't understand the `quote` macro from `proc-macro2` so we
# need to use `syn` to parse the input and then use `quote` to generate the
syn = { version = "2.0.95", features = ["full", "extra-traits"] }
quote = "^1"
proc-macro2 = "1.0.92"
paste = "1.0.14"
convert_case = "0.6.0"
sha256 = "1.5.0"
tokio-stream = "0.1.17"
lazy_static = "1.5.0"

[lib]
proc-macro = true

bench = false

[dev-dependencies]
insta = { version = "1.41.1", features = ["filters", "yaml"] }
pretty_assertions = "1.4.0"
prettyplease = "0.2.25"
sha256 = "1.5.0"
trybuild = "1.0.101"
jetstream = { path = "../../", features = ["server", "client"] }
jetstream_wireformat = { path = "../jetstream_wireformat" }
jetstream_client = { path = "../jetstream_client" }
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
turmoil = "0.6.4"
okstd = { version = "0.2.0", features = ["macros"] }


[[test]]
name = "macro"
path = "tests/macro/01-basic.rs"
