[package]
name = "jetstream_ufs"
version = "5.2.2"
edition = { workspace = true }
description = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
[dependencies]
jetstream_9p = { version = "5.2.2", path = "../jetstream_9p" }
jetstream_wireformat = { version = "5.2.2", path = "../jetstream_wireformat" }
jetstream_rpc = { version = "5.2.2", path = "../jetstream_rpc" }
serde = { version = "1.0.210", features = ["derive"] }
libc = "0.2.159"
tokio = { version = "1.40.0", features = ["full"] }
anyhow = "1.0.89"
