[package]
name = "jetstream_client"
version = "5.0.0"
edition = "2021"
description = "Jetstream is a RPC framework for Rust, based on the 9P protocol and QUIC."
license = "BSD-3-Clause"
repository = "https://github.com/sevki/jetstream"

[dependencies]
anyhow = "1.0.89"
futures = "0.3.30"
jetstream_9p = { version = "5.0.0", path = "../jetstream_9p" }
jetstream_rpc = { version = "5.0.0", path = "../jetstream_rpc" }
jetstream_wireformat = { version = "5.0.0", path = "../jetstream_wireformat", features = [
    "async",
] }
okstd = { version = "0.1.10" }
s2n-quic = "1.47.0"
